DROP TABLE Book;
DROP TABLE Category;

CREATE TABLE Book (
  isbn        VARCHAR(255) PRIMARY KEY,
  author      VARCHAR(255) NOT NULL,
  title       VARCHAR(255) NOT NULL,
  year        INTEGER NOT NULL,
  price       FLOAT NOT NULL);

CREATE TABLE Category (
  id          BIGINT PRIMARY KEY,
  name        VARCHAR(255) NOT NULL
 );

DROP SEQUENCE HIBERNATE_SEQUENCE;
CREATE SEQUENCE HIBERNATE_SEQUENCE;